grid-columns: 2

appareils: "psn.appareils" {
  shape: sql_table
  appareil_id: "INT" {constraint: primary_key}
  identifieur: "VARCHAR(255)"
  cle: "VARCHAR(255)" {constraint: unique}
  operating_system: "VARCHAR(50)"
  blacklist: "TINYINT(1)"
  firebase_token: "VARCHAR(255) NULL"
  revoked_at: "DATETIME NULL"
  revoked_reason: "ENUM NULL"
}

app_version_history: "psn.app_version_history" {
  shape: sql_table
  app_version_history_id: "INT" {constraint: primary_key}
  app_identifier: "VARCHAR(100)"
  version_identifier: "VARCHAR(50)"
  build: "DOUBLE"
  expired: "BIT(1)"
  available: "BIT(1)"
  beta_build: "BIT(1)"
}
