grid-columns: 1
grid-gap: 100

requete: "Requête entrante" {
  direction: right
  http_in: "Corps HTTP"
  dto: "DTO (validation)"
  service_in: "Service"
  repository: "Repository"
  entite_in: "Entité"
  bd: "BD" {shape: cylinder}

  http_in -> dto -> service_in -> repository -> entite_in -> bd
}

reponse: "Réponse sortante" {
  direction: right
  bd2: "BD" {shape: cylinder}
  entite_out: "Entité"
  adapter_out1: "Adapter"
  modele_out1: "Modèle métier"
  service_out: "Service"
  adapter_out2: "Adapter"
  dto_out: "DTO"
  http_out: "Corps HTTP"

  bd2 -> entite_out -> adapter_out1 -> modele_out1 -> service_out -> adapter_out2 -> dto_out -> http_out
}
